### ISSUE TITLE
Script errors: Deserialized.Microsoft.Exchange.Data.Directory.Management.ExchangeServer

### ISSUE THREAD

**Issue by red-erik** [junecastillote/Get-ExchangeHealth#2]
Hello,
I receive errors on all Database with this code (from debug file):
9/9/2019 4:16:29 PM : Server Status Check...
Cannot process argument transformation on parameter 'Server'. Cannot convert the "RMMX16P01" value of type 
"Deserialized.Microsoft.Exchange.Data.Directory.Management.ExchangeServer" to type 
"Microsoft.Exchange.Configuration.Tasks.ServerIdParameter".
    + CategoryInfo          : InvalidData: (:) [Test-ServiceHealth], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Test-ServiceHealth
    + PSComputerName        : tomx16p01.xxxxxx.xx

The same, another check fails with:
9/9/2019 4:16:45 PM : Server Component State...
Cannot process argument transformation on parameter 'Identity'. Cannot convert the "RMMX16P01" value of type 
"Deserialized.Microsoft.Exchange.Data.Directory.Management.ExchangeServer" to type 
"Microsoft.Exchange.Configuration.Tasks.ServerIdParameter".
    + CategoryInfo          : InvalidData: (:) [Get-ServerComponentState], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-ServerComponentState
    + PSComputerName        : tomx16p01.xxxxxxxx.xx

I have this error for ALL servers and it seems to be related on how the connection is made (Exchange EMS) and the remote execution of commands.
do you have any suggestions ?
Thank you in advance for your good work and for sharing.

Regards.

Red.

**Comment by junecastillote** [comment]
I totally missed this one and I am sorry for the super late response.

And yes, beginning Exchange 2013 that seems to be the case. It does not seem to happen if you are using the Exchange Management Shell (from the management tools), whether manual or by the task scheduler - which is why it is included in the [How To Use](https://github.com/junecastillote/Get-ExchangeHealth#how-to-use) section.
